import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/componentes/Aula2/Exercicio3/Menu";
import MenuLoja from "@/componentes/Aula3/Exercicio1/MenuLoja";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

      <div className="flex h-screen">
          
          <div className="flex justify-center items-center">
            {children}
          </div>
      </div>

      </body>
    </html>
  );
}

/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */